### ISSUE TITLE
Updating from v0.17.0 to v0.18.0 issue

### ISSUE THREAD

**Issue by qu1queee** [JulzDiverse/aviator#27]
Hi Julz,

I just updated to v0.18.0 and my aviator file is breaking when doing the `fly` feature. The following config:
```
fly:
  config: /tmp/final-pipeline.yml
  name: $PIPELINE
  target: $TARGET
  vars:
  - vars.yml
```
was working fine under v0.17.0, however when upgrading the version, that same part broke with the following:

```
YAML Parsing Failed: yaml: unmarshal errors:
  line 15: cannot unmarshal !!seq into map[string]string
```

Have you seen this behaviour?
