### ISSUE TITLE
[feature request] New merge type that doesn't require a file

### ISSUE THREAD

**Issue by gdankov** [JulzDiverse/aviator#38]
Hey Julz,

The suggestion here is to perform a standard merge, but instead of having to always specify files in the `with` section, we can directly write the yaml code we would like to merge.

For example, let's say we have the following aviator file:
```yaml
spruce:
- base: path/to/base.yml
  merge:
  - with_obj:
    foo:
      bar: 42
      baz: true
  to: result.yml
```

That would merge the base file with the following:
```yaml
foo:
  bar: 42
  baz: true
```

Why? Sometimes you want to merge something really tiny (2-3 lines) and creating a separate file for that can be an overkill.

Thanks 🙂
