### ISSUE TITLE
[feature request] Support setting array values

### ISSUE THREAD

**Issue by akshaymankar** [JulzDiverse/aviator#39]
Example:

input.yml
```yaml
foo:
  bar: 2000
```

avaitor.yml
```yaml
- base: input.yml
  modify:
    set:
    - path: .foo.baz
       value: [qux]
```
Expected output:
```yaml
foo:
  bar: 2000
  baz: [qux]
```
